spring:
  application.name: javascript-framework
  datasource:
    url: jdbc:h2:mem:javascriptframeworks;DB_CLOSE_DELAY=-1;
  h2.console:
    enabled: true
    path: "/h2"

management:
  info.git.mode: full
  endpoint:
    shutdown.enabled: true
    health.show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  name: ${spring.application.name}
