spring:
  application.name: javascript-framework
  datasource:
    url: jdbc:h2:~/javascriptframeworks;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;
    password: sa
    username: password
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2.console:
    enabled: true
    path: "/h2"

management:
  info.git.mode: full
  endpoint:
    shutdown.enabled: true
    health.show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  name: ${spring.application.name}
